name: scheduled
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.0.0
  hive_flutter: ^1.1.0 
  file_picker: ^8.1.7
  video_player: ^2.5.1
  shared_preferences: ^2.1.0
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  
  hive_generator: ^2.0.1  
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png


flutter:
  uses-material-design: true

  assets:
    - assets/questionnaire.csv
    - assets/explanations.csv

    - assets/images/app_icon.png
    - assets/images/log_in.png
    - assets/images/sign_up.png
    - assets/images/logo_top.png
    - assets/images/information.png
    - assets/images/coloured_info.png

    - assets/videos/priority.mp4
    - assets/videos/multi-level.mp4
    - assets/videos/fcfs.mp4

    - assets/task_input.json


  
